// AUTO-GENERATED - DO NOT EDIT
// Generated by Claude from orris backend
// Source: github.com/orris-inc/orris/sdk/agent

// Package agent provides a Go SDK for interacting with the Orris Agent API.
package api

// NodeConfig represents the node configuration returned by the API.
// Compatible with sing-box inbound configuration.
type NodeConfig struct {
	NodeSID           string       `json:"node_id"`                     // Node SID (Stripe-style: node_xxx)
	Protocol          string       `json:"protocol"`                    // shadowsocks or trojan
	ServerHost        string       `json:"server_host"`                 // Server hostname or IP address
	ServerPort        int          `json:"server_port"`                 // Server port number
	EncryptionMethod  string       `json:"encryption_method,omitempty"` // Encryption method for Shadowsocks
	ServerKey         string       `json:"server_key,omitempty"`        // Server password for SS
	TransportProtocol string       `json:"transport_protocol"`          // Transport protocol (tcp, ws, grpc)
	Host              string       `json:"host,omitempty"`              // WebSocket host header
	Path              string       `json:"path,omitempty"`              // WebSocket path
	ServiceName       string       `json:"service_name,omitempty"`      // gRPC service name
	SNI               string       `json:"sni,omitempty"`               // TLS Server Name Indication
	AllowInsecure     bool         `json:"allow_insecure"`              // Allow insecure TLS connection
	EnableVless       bool         `json:"enable_vless"`
	EnableXTLS        bool         `json:"enable_xtls"`
	SpeedLimit        uint64       `json:"speed_limit"`
	DeviceLimit       int          `json:"device_limit"`
	RuleListPath      string       `json:"rule_list_path,omitempty"` // Deprecated: use Route instead
	Route             *RouteConfig `json:"route,omitempty"`          // Routing configuration for traffic splitting
	Outbounds         []Outbound   `json:"outbounds,omitempty"`      // Outbound configs for nodes referenced in route rules
}

// Outbound represents a sing-box outbound configuration.
// Used when route rules reference other nodes as outbounds.
type Outbound struct {
	Type   string `json:"type"`        // Protocol type: shadowsocks, trojan, direct, block
	Tag    string `json:"tag"`         // Unique identifier for the outbound (node SID)
	Server string `json:"server"`      // Server hostname or IP address
	Port   int    `json:"server_port"` // Server port number

	// Shadowsocks specific fields
	Method     string `json:"method,omitempty"`      // Encryption method for SS
	Password   string `json:"password,omitempty"`    // Password for SS/Trojan
	Plugin     string `json:"plugin,omitempty"`      // SIP003 plugin name
	PluginOpts string `json:"plugin_opts,omitempty"` // Plugin options string

	// TLS fields (for Trojan)
	TLS *OutboundTLS `json:"tls,omitempty"` // TLS configuration

	// Transport fields (for Trojan ws/grpc)
	Transport *OutboundTransport `json:"transport,omitempty"` // Transport configuration
}

// OutboundTLS represents TLS configuration for outbound.
type OutboundTLS struct {
	Enabled    bool     `json:"enabled"`               // Enable TLS
	ServerName string   `json:"server_name,omitempty"` // SNI
	Insecure   bool     `json:"insecure,omitempty"`    // Allow insecure TLS
	DisableSNI bool     `json:"disable_sni,omitempty"` // Disable SNI
	ALPN       []string `json:"alpn,omitempty"`        // ALPN protocols
}

// OutboundTransport represents transport configuration for outbound.
type OutboundTransport struct {
	Type        string            `json:"type"`                   // Transport type: ws, grpc
	Path        string            `json:"path,omitempty"`         // WebSocket path
	Headers     map[string]string `json:"headers,omitempty"`      // Custom headers for WS
	ServiceName string            `json:"service_name,omitempty"` // gRPC service name
}

// RouteConfig represents the routing configuration for sing-box.
// It defines how traffic should be routed based on matching rules.
type RouteConfig struct {
	Rules []RouteRule `json:"rules,omitempty"` // Ordered list of routing rules
	Final string      `json:"final"`           // Default outbound when no rules match (direct/block/proxy or node_xxx)
}

// RouteRule represents a single routing rule, compatible with sing-box route rule.
type RouteRule struct {
	// Domain matching
	Domain        []string `json:"domain,omitempty"`         // Exact domain match
	DomainSuffix  []string `json:"domain_suffix,omitempty"`  // Domain suffix match
	DomainKeyword []string `json:"domain_keyword,omitempty"` // Domain keyword match
	DomainRegex   []string `json:"domain_regex,omitempty"`   // Domain regex match

	// IP matching
	IPCIDR       []string `json:"ip_cidr,omitempty"`        // Destination IP CIDR match
	SourceIPCIDR []string `json:"source_ip_cidr,omitempty"` // Source IP CIDR match
	IPIsPrivate  bool     `json:"ip_is_private,omitempty"`  // Match private/LAN IP addresses

	// GeoIP/GeoSite matching
	GeoIP   []string `json:"geoip,omitempty"`   // GeoIP country codes (cn, us, etc.)
	GeoSite []string `json:"geosite,omitempty"` // GeoSite categories (cn, google, etc.)

	// Port matching
	Port       []int `json:"port,omitempty"`        // Destination port match
	SourcePort []int `json:"source_port,omitempty"` // Source port match

	// Protocol/Network matching
	Protocol []string `json:"protocol,omitempty"` // Sniffed protocol match (http, tls, etc.)
	Network  []string `json:"network,omitempty"`  // Network type match (tcp, udp)

	// Rule set reference
	RuleSet []string `json:"rule_set,omitempty"` // Rule set references

	// Action
	Outbound string `json:"outbound"` // Action: direct/block/proxy or node_xxx (for routing to specific node)
}

// IsTrojan returns true if the node is configured for Trojan protocol.
func (c *NodeConfig) IsTrojan() bool {
	return c.Protocol == "trojan"
}

// IsShadowsocks returns true if the node is configured for Shadowsocks protocol.
func (c *NodeConfig) IsShadowsocks() bool {
	return c.Protocol == "shadowsocks"
}

// Subscription represents an individual subscription authorized for the node.
type Subscription struct {
	SubscriptionSID string `json:"subscription_id"` // Subscription SID (Stripe-style: sub_xxx)
	Password        string `json:"password"`
	Name            string `json:"name"`
	SpeedLimit      uint64 `json:"speed_limit"`
	DeviceLimit     int    `json:"device_limit"`
	ExpireTime      int64  `json:"expire_time"`
}

// TrafficReport represents traffic data for a single subscription.
type TrafficReport struct {
	SubscriptionSID string `json:"subscription_id"` // Subscription SID (Stripe-style: sub_xxx)
	Upload          int64  `json:"upload"`
	Download        int64  `json:"download"`
}

// NodeStatus represents node system status for reporting to the server
// All metrics should be collected using prometheus/procfs or equivalent libraries
type NodeStatus struct {
	// System resources
	CPUPercent    float64 `json:"cpu_percent"`    // CPU usage percentage (0-100)
	MemoryPercent float64 `json:"memory_percent"` // Memory usage percentage (0-100)
	MemoryUsed    uint64  `json:"memory_used"`    // Memory used in bytes
	MemoryTotal   uint64  `json:"memory_total"`   // Total memory in bytes
	MemoryAvail   uint64  `json:"memory_avail"`   // Available memory in bytes (from procfs Meminfo)
	DiskPercent   float64 `json:"disk_percent"`   // Disk usage percentage (0-100)
	DiskUsed      uint64  `json:"disk_used"`      // Disk used in bytes
	DiskTotal     uint64  `json:"disk_total"`     // Total disk in bytes
	UptimeSeconds int64   `json:"uptime_seconds"` // System uptime in seconds

	// System load (from procfs LoadAvg)
	LoadAvg1  float64 `json:"load_avg_1"`  // 1-minute load average
	LoadAvg5  float64 `json:"load_avg_5"`  // 5-minute load average
	LoadAvg15 float64 `json:"load_avg_15"` // 15-minute load average

	// Network statistics (from procfs NetDev, excluding loopback)
	NetworkRxBytes uint64 `json:"network_rx_bytes"` // Total received bytes across all interfaces
	NetworkTxBytes uint64 `json:"network_tx_bytes"` // Total transmitted bytes across all interfaces

	// Network bandwidth (calculated by agent from delta/time)
	NetworkRxRate uint64 `json:"network_rx_rate"` // Current receive rate in bytes per second
	NetworkTxRate uint64 `json:"network_tx_rate"` // Current transmit rate in bytes per second

	// Connection statistics
	TCPConnections int `json:"tcp_connections"` // Number of TCP connections
	UDPConnections int `json:"udp_connections"` // Number of UDP connections

	// Network info
	PublicIPv4 string `json:"public_ipv4,omitempty"` // Public IPv4 address
	PublicIPv6 string `json:"public_ipv6,omitempty"` // Public IPv6 address

	// Agent info
	AgentVersion string `json:"agent_version,omitempty"` // Agent software version (e.g., "1.2.3")
	Platform     string `json:"platform,omitempty"`      // OS platform (linux, darwin, windows)
	Arch         string `json:"arch,omitempty"`          // CPU architecture (amd64, arm64, arm, 386)

	// CPU details
	CPUCores     int     `json:"cpu_cores"`      // Number of CPU cores
	CPUModelName string  `json:"cpu_model_name"` // CPU model name
	CPUMHz       float64 `json:"cpu_mhz"`        // CPU frequency in MHz

	// Swap memory
	SwapTotal   uint64  `json:"swap_total"`   // Total swap in bytes
	SwapUsed    uint64  `json:"swap_used"`    // Used swap in bytes
	SwapPercent float64 `json:"swap_percent"` // Swap usage percentage

	// Disk I/O
	DiskReadBytes  uint64 `json:"disk_read_bytes"`  // Total disk read bytes
	DiskWriteBytes uint64 `json:"disk_write_bytes"` // Total disk write bytes
	DiskReadRate   uint64 `json:"disk_read_rate"`   // Disk read rate in bytes per second
	DiskWriteRate  uint64 `json:"disk_write_rate"`  // Disk write rate in bytes per second
	DiskIOPS       uint64 `json:"disk_iops"`        // Disk IOPS

	// Pressure Stall Information (PSI)
	PSICPUSome    float64 `json:"psi_cpu_some"`    // CPU pressure (some)
	PSICPUFull    float64 `json:"psi_cpu_full"`    // CPU pressure (full)
	PSIMemorySome float64 `json:"psi_memory_some"` // Memory pressure (some)
	PSIMemoryFull float64 `json:"psi_memory_full"` // Memory pressure (full)
	PSIIOSome     float64 `json:"psi_io_some"`     // I/O pressure (some)
	PSIIOFull     float64 `json:"psi_io_full"`     // I/O pressure (full)

	// Network extended stats
	NetworkRxPackets uint64 `json:"network_rx_packets"` // Received packets
	NetworkTxPackets uint64 `json:"network_tx_packets"` // Transmitted packets
	NetworkRxErrors  uint64 `json:"network_rx_errors"`  // Receive errors
	NetworkTxErrors  uint64 `json:"network_tx_errors"`  // Transmit errors
	NetworkRxDropped uint64 `json:"network_rx_dropped"` // Receive dropped packets
	NetworkTxDropped uint64 `json:"network_tx_dropped"` // Transmit dropped packets

	// Socket statistics
	SocketsUsed      int `json:"sockets_used"`       // Total used sockets
	SocketsTCPInUse  int `json:"sockets_tcp_in_use"` // TCP sockets in use
	SocketsUDPInUse  int `json:"sockets_udp_in_use"` // UDP sockets in use
	SocketsTCPOrphan int `json:"sockets_tcp_orphan"` // TCP orphan connections
	SocketsTCPTW     int `json:"sockets_tcp_tw"`     // TCP TIME_WAIT connections

	// Process statistics
	ProcessesTotal   uint64 `json:"processes_total"`   // Total processes
	ProcessesRunning uint64 `json:"processes_running"` // Running processes
	ProcessesBlocked uint64 `json:"processes_blocked"` // Blocked processes

	// File descriptors
	FileNrAllocated uint64 `json:"file_nr_allocated"` // Allocated file descriptors
	FileNrMax       uint64 `json:"file_nr_max"`       // Maximum file descriptors

	// Context switches and interrupts
	ContextSwitches uint64 `json:"context_switches"` // Context switches count
	Interrupts      uint64 `json:"interrupts"`       // Interrupts count

	// Kernel info
	KernelVersion string `json:"kernel_version"` // Kernel version
	Hostname      string `json:"hostname"`       // System hostname

	// Virtual memory statistics
	VMPageIn  uint64 `json:"vm_page_in"`  // Pages paged in
	VMPageOut uint64 `json:"vm_page_out"` // Pages paged out
	VMSwapIn  uint64 `json:"vm_swap_in"`  // Swap pages in
	VMSwapOut uint64 `json:"vm_swap_out"` // Swap pages out
	VMOOMKill uint64 `json:"vm_oom_kill"` // OOM kill count

	// Entropy pool
	EntropyAvailable uint64 `json:"entropy_available"` // Available entropy
}

// OnlineSubscription represents an online subscription connection.
type OnlineSubscription struct {
	SubscriptionSID string `json:"subscription_id"` // Subscription SID (Stripe-style: sub_xxx)
	IP              string `json:"ip"`
}

// TrafficReportResult represents the result of a traffic report.
type TrafficReportResult struct {
	SubscriptionsUpdated int `json:"subscriptions_updated"`
}

// OnlineSubscriptionsResult represents the result of updating online subscriptions.
type OnlineSubscriptionsResult struct {
	OnlineCount int `json:"online_count"`
}

// UpdatePayload is the payload received in update command.
// Agent should download the binary from DownloadURL and verify with Checksum.
type UpdatePayload struct {
	Version     string `json:"version"`      // Target version (e.g., "v1.2.3")
	DownloadURL string `json:"download_url"` // Download URL for the binary
	Checksum    string `json:"checksum"`     // SHA256 checksum (if available)
}

// apiResponse represents the standard API response structure.
type apiResponse struct {
	Success bool   `json:"success"`
	Message string `json:"message,omitempty"`
	Data    any    `json:"data,omitempty"`
}
